### ISSUE TITLE
Explore a in-cluster VPN solution to access my home network while away

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k3s-gitops#28]
I need to find out a way to have a in cluster VPN, currently I am using PiVPN on a separate device.

Possibly:

https://github.com/helm/charts/tree/master/stable/openvpn

https://github.com/kylemanna/docker-openvpn
https://github.com/0xERR0R/openvpn_exporter
https://github.com/kumina/openvpn_exporter

**Comment by onedr0p** [comment]
https://github.com/cmulk/wireguard-docker

**Comment by carpenike** [comment]
Will probably need to pick a network and add a route on your edge device to your k8s node.

**Comment by onedr0p** [comment]
I have a network for VPN users in my unifi controller, I wonder if that can be used.

**Comment by carpenike** [comment]
Sure, but you need to add a route that tells the USG that the route is no longer local

**Comment by jp83** [comment]
Would you guys mind describing your network infrastructure here, in particular how you (or plan to) route and dns?

In my case I just moved to Mikrotik for edge router (was ubiquiti) and thinking of separating dhcp & dns to pihole, so reevaluating.  My k8s nodes (VMs) are all on the main users vlan.  I use traefik for reverse proxy with metallb for a fixed IP on my network.  With a wildcard dns for *.k8s.domain.com any (internally) exposed services resolve to that IP.  Some services are also given external domain names which point to the cname for my home WAN IP.  With https port forwarding through NAT to that IP, and with name recognition in traefik pass through.  Not sure if this is a security consideration using just name resolution.  At one time I thought I'd have 2 traefik proxies one for internal and another for external., but it works.

My specific question is if your defining your own domain in k8s and pointing a subdomain from your main networks dns to k8s as authority (I think I've seen some examples like this just not sure trade offs vs how I'm doing int).

Felt like I needed to ask the above as underlying questions first.  In reference to this issue, I've looked at running OpenVPN in k8s, but the examples were always to get internal to k8s, and I just wanted it as a remote access server to my network, so that's why I'm curious more details about the routing you mentioned above to accomplish that.

I had a basic openvpn server running on my Edgerouter Lite, but now going with just ipsec in Mikrotik for a couple different sites (like parents house for remote backup).  I'd still like a more fail proof roadwarrior connection so I can get in remotely from phone, laptop, or travel router with a temporary connection that may be more stringently fire-walled.  In my earlier docker setup I was using sslh to multiplex https, ssh, and openvpn on a single port, but not sure how to put that out front while still running in k8s..

**Comment by onedr0p** [comment]
@jp83 

I have a Unifi set up. I recently deployed [blocky](https://github.com/onedr0p/k3s-gitops/blob/master/deployments/default/blocky/blocky.yaml) instead of pihole because I can scale it and it's not stateful, also works well with Grafana for collecting stats:

![image](https://user-images.githubusercontent.com/213795/77238869-ba27bc00-6baa-11ea-9ce6-8f1abe174d61.png)

Blocky can also be set up for internal DNS mapping (e.g. `192.168.1.100 printer.lan`). I also force all clients on my network to use that LoadBalancerIP by editing the [config.gateway.json](https://github.com/onedr0p/k3s-gitops/blob/master/docs/config.gateway-example.json) as described [here](https://github.com/onedr0p/k3s-gitops/blob/master/docs/unifi.md) on my Unifi Controller.

Diving more into my network setup. My domains are managed in Cloudflare and I use their free services as a firewall (WAF). My home IP gets updated using the settings in the `config.gateway.json` file above. I have my domain as a A record and my subdomains as CNAMES proixed thru Cloudflares servers. When a request comes it to my network it has to get past Cloudflares WAF and get past by firewall rules on my Unifi Controller which only allow Cloudflare IPs when requests are to port 80 and 443. In order to get the clients real IP I had to update my [nginx-ingress](https://github.com/onedr0p/k3s-gitops/blob/master/deployments/kube-system/nginx-ingress/nginx-ingress.yaml) deployment to let that happen.

As for OpenVPN in k8s I am as lost as you. I would like to use the existing CIDR I set up in Unifi for my VPN network if possible. Maybe @carpenike can dive a bit more into how that can be achieved.

**Comment by onedr0p** [comment]
A couple other products to explore:

https://www.zerotier.com/

https://tailscale.com/

**Comment by onedr0p** [comment]
Decided to use pivpn w/ wireguard on a device outside the cluster.
